// <auto-generated />
using System;
using AppointmentConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppointmentConsoleApp.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20191107062532_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppointmentConsoleApp.AppointmentInfo", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatenTime");

                    b.Property<string>("GuestUser")
                        .IsRequired();

                    b.Property<string>("HostUser")
                        .IsRequired();

                    b.Property<int>("HostUserID");

                    b.Property<string>("Status");

                    b.Property<string>("Subject")
                        .HasMaxLength(100);

                    b.HasKey("AppointmentID")
                        .HasName("PK_Appointments");

                    b.HasIndex("HostUserID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AppointmentConsoleApp.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<long>("PhoneNumber");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("UserId")
                        .HasName("PK_Users");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppointmentConsoleApp.AppointmentInfo", b =>
                {
                    b.HasOne("AppointmentConsoleApp.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("HostUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
